# Generated by Django 5.2.1 on 2025-11-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_medicine_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
