# Generated by Django 5.2.1 on 2025-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Addpiont',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
