# Generated by Django 5.2.1 on 2025-11-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine_addpiont'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opertionmoney',
            name='Date1',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opertionmoney',
            name='Method',
            field=models.CharField(choices=[('Add', 'Add'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opertionmoney',
            name='MyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.wallet'),
        ),
        migrations.AlterField(
            model_name='opertionmoney',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='money_images/'),
        ),
        migrations.AlterField(
            model_name='opertionmoney',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='Amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
