# Generated by Django 5.2.1 on 2025-11-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_opertionmoney_date1_alter_opertionmoney_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opertionmoney',
            name='Account',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
