# Generated by Django 5.2.1 on 2025-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_opertionmoney_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opertionmoney',
            name='Account',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
