# Generated by Django 5.2.1 on 2025-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customeraddress_x_customeraddress_y_comment_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default=11, max_length=15),
            preserve_default=False,
        ),
    ]
