# Generated by Django 5.2.1 on 2025-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comment_options_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
