# Generated by Django 5.2.1 on 2025-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_payment_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ManyToManyField(blank=True, related_name='order_prescription', to='app.prescription'),
        ),
    ]
