# Generated by Django 5.2.1 on 2025-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_order_prescription_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='loction_x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='loction_y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
