# Generated by Django 5.2.1 on 2025-11-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
    ]
