# Generated by Django 5.2.1 on 2025-11-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='his_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_driver', to='app.driver'),
        ),
    ]
