# Generated by Django 5.2.1 on 2025-12-15 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_his_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='x',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='y',
        ),
        migrations.AddField(
            model_name='driver',
            name='current_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
