# Generated by Django 5.2.1 on 2026-01-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_driver_x_remove_driver_y_driver_current_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_delivery',
        ),
    ]
