# Generated by Django 5.2.1 on 2026-01-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_order_price_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='current_x',
            new_name='current_latitude',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='current_y',
            new_name='current_longitude',
        ),
        migrations.AlterField(
            model_name='order',
            name='his_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.driver'),
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='app.driver')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
