# Generated by Django 5.2.1 on 2026-01-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_current_x_driver_current_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='current_latitude',
            new_name='current_x',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='current_longitude',
            new_name='current_y',
        ),
        migrations.AlterField(
            model_name='order',
            name='his_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_driver', to='app.driver'),
        ),
        migrations.DeleteModel(
            name='DriverLocationHistory',
        ),
    ]
