# Generated by Django 5.2.1 on 2026-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_current_latitude_driver_current_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opertionmoney',
            name='type',
            field=models.CharField(choices=[('Syriatel', 'Syriatel'), ('MTN', 'MTN')], max_length=20),
        ),
    ]
