# Generated by Django 5.2.1 on 2025-11-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_birthy_day_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthy_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
