# Generated by Django 5.2.1 on 2025-11-22 16:49

import User.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_birthy_day_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthy_day',
            field=models.DateField(default='2002-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=User.models.upload_to),
        ),
    ]
