# Generated by Django 5.2.1 on 2025-12-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_birthy_day_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthy_day',
            field=models.DateField(null=True),
        ),
    ]
